### ISSUE TITLE
illegal memory access error

### ISSUE THREAD

**Issue by Unrealluver** [sustcsonglin/flash-linear-attention#7]
Hi Songlin,

Thanks for your great work! I tried some comparative experiments on FLA recently and it presents great performance! But I faced an error when I increased the dimension to 1152 and set the head num to 16. The details of this error are shown below:

```
n136-180-028:1707397:1709473 [6] include/alloc.h:124 NCCL WARN Cuda failure 700 'an illegal memory access was encountered'
n136-180-028:1707397:1709473 [6] NCCL INFO include/alloc.h:245 -> 1
```

Could you give me some advice or guidance about this? Thanks a lot! By the way, could I get your WeChat for further communication? :D

Yours,
Lianghui

**Comment by Unrealluver** [comment]
**[Additional information]** Our input for GLA has a shape of [B, 4, 16, 16] and this error only occurs when `B` is 8 or bigger. If we set B to 4 or below, we would not meet this problem. So I guess maybe this is related to some triton implementation details?

**Comment by sustcsonglin** [comment]
My wechat id is `sonta203242`

**Comment by pUmpKin-Co** [comment]
Same problem.
I test through Chunk and FusedRecurent vesion but both failed on this line with "illegal memory access":
```python
o = o.sum(1)
```

My initial guess was OOM, so I checked the peak memory usage and found it to be within acceptable limits. Interestingly, the process functions correctly when the sequence length is set to 512. 
That is, when I conducted experiments using a 1.4B model with a batch size of 1, sequence length of 2048, and dimension of 2048, it failed, but it succeeded with a sequence length of 512.

I'm confused by this because all experiments were run on an A100, and I didn't expect memory consumption to be high enough to cause issues, especially since I've frozen the parameters.

Any suggestions? (Sorry.... as I am quite new to kernel programming.)
